# ------------------------
# Adopta Agency Blueprint
# This is meant to be a blueprint for opening up data.
# You control everything about this site, here in the _config.yml
# All data is stored under /data
# All API definitions are stored under /api
# Tell your story via the /blog
# Manage all conversations through this project's Github issues
# ------------------------

# Give your peject a title, description, some tags, and URL to Github home page
project_title: Adopta Blueprint
project_description: This is the master blueprint for the Adopta.Agency. The goal is to move forward the conversation around any government data, making it more accessible as CSV and JSON files, and deploying simple APIs when possible.
project_url: http://adopta-agency.github.io/adopta-blueprint/
project_tags:
  - tag: blueprint
  - tag: open data

github_user: adopta-agency
github_repo: adopta-blueprint

# ---------
# This is the section where you describe the data involved in your project.
# ---------
data_show: yes
data_nav: yes
data_title: Data Files
data_description: This is just a sample set of dataset to show what is possible. Your mission if you choose to accept it, is find your dataset at data.gov, or amongst the inventory of each federal agencies data.json files. Once you have found your datasatets, you can clean up, publish, and share here.
data_footer: The goal of publishing these CSV and JSON alternatives is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

# You can add one or many data sets here, with a title, and link to CSV and JSON file
data:
  - title: "Farmers Markets"
    csv_url: "https://kinlane.github.io/adopta-blueprint/data/famers_markets.csv"
    json_url: "https://kinlane.github.io/adopta-blueprint/data/famers_markets.json"

# ---------
# APIs
# ---------

api_show: yes
api_nav: yes
api_title: APIs
api_description: This is a sample API generated from the dataset above. It is described using Swagger which allows the generation of interactive documentation, while also describing the meta data and surface area of an API.
api_footer: The goal of launching these APIs is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

api:
  - title: Farmers Markets
    swagger_url: https://adopta-agency.github.io/adopta-blueprint/api/farmers_markets.json

# ---------
# Showcase
# ---------

showcase_show: yes
showcase_nav: no
showcase_title: Showcase
showcase_description: These are some of the things being build on top of this open data and APIs.
showcase_footer: This project is designed to be used, and extended, please share what you have built so it can be included.

showcase:
  - title: Showcase Item One
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Two
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Four
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com

# ---------
# FAQ
# ---------

faq_show: yes
faq_nav: no
faq_title: FAQ
faq_description: These are some of the common questions that need answering or get asked as part of this work.
faq_footer: Questions that get submitted via the projects Github issue managment are sometimes added here.

faq:
  - question: Why are you doing this?
    answer: I want to make data more accessible and usable, encouraging people to build it into more websites, applications, visualizations, and anywhere it can be used.
  - question: Where did this data come from?
    answer: It could come from data.gov, one of the data.json files of government agencies, or any other location you find the data you need.
  - question: What are you planning on doing with this data?
    answer: You can visit the <a href="https://kinlane.github.io/adopta-blueprint/roadmap/">roadmap for more information.
  - question: How do I talk to someone behind this project?
    answer: This site runs on Github Pages, and relies on Github issue management for support. <a href="https://github.com/kinlane/adopta-blueprint/issues/new">Go ahead and submit an issue</a> via the project repository.

# ---------
# Team
# ---------

team_show: yes
team_nav: no
team_title: Team
team_description: This is a solo project conducted by Kin Lane as part of the Adopta.Agency project.
team_footer: If you would like to get involved with this work, please submit an issue via the Github repo.

team:
  - name: Kin Lane
    description: The API Evangelist, working to make data, content, and other digital resources more accessible.
    url: http://kinlane.com

# ---------
# Tools
# ---------

tools_show: yes
tools_nav: no
tools_title: Tools
tools_description: This is a list of tools that are used as part of this project.
tools_footer: We share the tools we used to help others understand how to recreate the work.

tools:
  - title: Github
    description: A social network built around software development platform Git.
    url: http://github.com
  - title: Github Pages
    description: Websites for projects that are hosted directly from a GitHub repository.
    url: https://pages.github.com/
  - title: Google Spreadsheets
    description: Cloud-based spreadsheets as part of the overall Google Dirve platform.
    url: https://www.google.com/drive/
  - title: API Spark
    description: A platform for the creation, hosting, management, and consumption of web APIs.
    url: http://restlet.com/products/apispark/
  - title: CSV Converter
    description: A CSV conversion tool that runs on Github, created from Mr. Data Converter.
    url: http://kinlane.github.io/csv-converter/

# ---------
# Blog
# ---------

permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"
blog_nav: yes

# ---------
# Support
# ---------

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@apievangelist.com
support_twitter: kinlane

# ---------
# Roadmap
# ---------

roadmap_show: yes
roadmap_nav: yes

# ---------
# Change Log
# ---------

changelog_show: yes
changelog_nav: yes

# ---------
# General Settings
# ---------

#versioning your peojct is good
version:      1.1.1

#some configurations for the site
markdown:     rdiscount
permalink:    pretty
pygments:     true


#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
