# ------------------------
# Adopta Agency Blueprint
# This is meant to be a blueprint for opening up data.
# You control everything about this site, here in the _config.yml
# All data is stored under /data
# All API definitions are stored under /api
# Tell your story via the /blog
# Manage all conversations through this project's Github issues
# ------------------------

# Give your peject a title, description, some tags, and URL to Github home page
project_title: Adopta Blueprint
project_description: This is the master blueprint for the <a href="http://adopta.agency">Adopta.Agency</a>. The goal of this work is to move forward the conversation around any public datas, making it more accessible as CSV and JSON files and deploying simple APIs when possible.
project_url: http://adopta-agency.github.io/adopta-blueprint/
project_tags:
  - tag: blueprint
  - tag: open data

github_user: adopta-agency
github_repo: adopta-blueprint

# ---------
# This is the section where you describe the data involved in your project.
# ---------
data_show: yes
data_nav: yes
data_title: Data Files
data_description: This is just a sample set of dataset to show what is possible. Your mission, if you choose to accept, is to find a dataset at data.gov, or amongst the inventory of each federal agencies data.json files. Once you have found your datasatets, you can clean up, publish, and share here.
data_footer: The goal of publishing these CSV and JSON alternatives is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

# You can add one or many data sets here, with a title, and link to CSV and JSON file
data:
  - title: "Farmers Markets"
    source_url: https://catalog.data.gov/dataset/farmers-markets-geographic-data
    csv_url: "http://adopta-agency.github.io/adopta-blueprint/data/farmers_markets.csv"
    json_url: "http://adopta-agency.github.io/adopta-blueprint/data/farmers_markets.json"

# ---------
# APIs
# ---------

api_show: yes
api_nav: yes
api_title: APIs
api_description: This is a sample API generated from the dataset above. It is described using Swagger which allows the generation of interactive documentation, while also describing the meta data and surface area of an API.
api_footer: The goal of launching these APIs is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

api:
  - title: Farmers Markets
    swagger_url: http://adopta-agency.github.io/adopta-blueprint/api/farmers_markets.json

# ---------
# Showcase
# ---------

showcase_show: yes
showcase_nav: no
showcase_title: Showcase
showcase_description: This is a showcase of what is being build on top of this open data and APIs. Right now it is just sample data, but when you launch for your project, you can showcase everything that is being developed.
showcase_footer: This project is designed to be used, and extended, please share what you have built so it can be included here on the showcase, for others to find.

showcase:
  - title: Showcase Item One
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Two
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Four
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com

# ---------
# FAQ
# ---------

faq_show: yes
faq_nav: no
faq_title: FAQ
faq_description: These are some of the common questions that need answering, or get asked as part of the work around this project.
faq_footer: Questions that get submitted via the projects Github issue managment are sometimes added here.

faq:
  - question: Why are you doing this?
    answer: I want to make data more accessible and usable, encouraging people to build it into more websites, applications, visualizations, and anywhere it can be used.
  - question: Where did this data come from?
    answer: It could come from data.gov, one of the data.json files of government agencies, or any other location you find the data you need.
  - question: What are you planning on doing with this data?
    answer: You can visit the <a href="http://adopta-agency.github.io/adopta-blueprint/roadmap/">roadmap</a> for more information.
  - question: How do I talk to someone behind this project?
    answer: This site runs on Github Pages, and relies on Github issue management for support. <a href="https://github.com/kinlane/adopta-blueprint/issues/new">Go ahead and submit an issue</a> via the project repository.

# ---------
# Team
# ---------

team_show: yes
team_nav: no
team_title: Team
team_description: This is a solo project conducted by Kin Lane as part of the Adopta.Agency project.
team_footer: If you would like to get involved with this work, please submit an issue via the Github repo.

team:
  - name: Kin Lane
    description: The API Evangelist, working to make data, content, and other digital resources more accessible.
    url: http://kinlane.com
  - name: Audrey Watters
    description: writer @hackeducation, ed-tech's Cassandra, author of The Monsters of Education Technology.
    url: http://audreywatters.com/

# ---------
# Tools
# ---------

tools_show: yes
tools_nav: no
tools_title: Tools
tools_description: This is a list of tools that are used as part of this project.
tools_footer: We share the tools we used to help others understand how to recreate the work.

tools:
  - title: Github
    description: Social Project Platform
    url: http://github.com
  - title: Github Pages
    description: Free Project Hosting
    url: https://pages.github.com/
  - title: Google Spreadsheets
    description: Web-based Spreadsheets
    url: https://www.google.com/drive/
  - title: API Spark
    description: API Deployment From Spreadsheets.
    url: http://restlet.com/products/apispark/
  - title: CSV Converter
    description: CSV to JSON Converter
    url: http://kinlane.github.io/csv-converter/converter.html
  - title: JSON Editor Online
    description: JSON Editor
    url: http://www.jsoneditoronline.org/
  - title: D3.js
    description: Visualizations from CSV and JSON files.
    url: http://d3js.org/

# ---------
# Blog
# ---------

permalink: /:categories/:year/:month/:day/:title/
paginate: 50
paginate_path: "/blog/page:num/"
blog_nav: yes

# ---------
# Support
# ---------

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@apievangelist.com
support_twitter: kinlane

# ---------
# Roadmap
# ---------

roadmap_show: yes
roadmap_nav: yes

# ---------
# Change Log
# ---------

changelog_show: yes
changelog_nav: yes

# ---------
# General Settings
# ---------

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
